# Generated by Django 4.2 on 2024-08-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_donor_subcsription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="subcsription",
            field=models.TextField(
                choices=[
                    ("Active", "Подписка активна"),
                    ("Inactive", "Подписка отсутствует"),
                    ("Lost", "Подписка утрачена"),
                ],
                default=False,
                verbose_name="Статус подписки у донора",
            ),
        ),
    ]
