# Generated by Django 4.2 on 2024-08-19 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_alter_donor_subcsription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donor",
            old_name="subcsription",
            new_name="subscription",
        ),
    ]
