# Generated by Django 4.2 on 2024-08-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloudpayments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudpayment",
            name="donat",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Размер пожертвования"
            ),
        ),
    ]
